update.packages(repos='http://www.icesi.edu.co/CRAN/')
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
biocLite("limma")
biocLite("BiocParallel")
biocLite("GO.db")
biocLite("edgeR")
install.packages("UpSetR", repos='http://www.icesi.edu.co/CRAN/')
install.packages("stringr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("tidyr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("kableExtra", repos='http://www.icesi.edu.co/CRAN/')
install.packages("knitr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("RColorBrewer", repos='http://www.icesi.edu.co/CRAN/')
install.packages("devtools", repos='http://www.icesi.edu.co/CRAN/')
install.packages("pheatmap", quiet=TRUE, repos='http://www.icesi.edu.co/CRAN/')
install.packages("car", repos='http://www.icesi.edu.co/CRAN/')
install.packages("knitr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("VennDiagram", repos='http://www.icesi.edu.co/CRAN/')
install.packages("rmarkdown", repos='http://www.icesi.edu.co/CRAN/')
install.packages("caTools", repos='http://www.icesi.edu.co/CRAN/')
install.packages("gdata", repos='http://www.icesi.edu.co/CRAN/')
install.packages("dplyr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("pander", repos='http://www.icesi.edu.co/CRAN/')
install.packages("KEGGREST", repos='http://www.icesi.edu.co/CRAN/')
install.packages("metagenomeSeq", repos='http://www.icesi.edu.co/CRAN/')
install.packages("vegan", repos='http://www.icesi.edu.co/CRAN/')
install.packages("gplots", repos='http://www.icesi.edu.co/CRAN/')
