install.packages("UpSetR", repos='http://www.icesi.edu.co/CRAN/')
install.packages("stringr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("tidyr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("kableExtra", repos='http://www.icesi.edu.co/CRAN/')
install.packages("knitr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("RColorBrewer", repos='http://www.icesi.edu.co/CRAN/')
install.packages("devtools", repos='http://www.icesi.edu.co/CRAN/')
install.packages("pheatmap", quiet=TRUE, repos='http://www.icesi.edu.co/CRAN/')
install.packages("car", repos='http://www.icesi.edu.co/CRAN/')
install.packages("knitr", repos='http://www.icesi.edu.co/CRAN/')
install.packages("VennDiagram", repos='http://www.icesi.edu.co/CRAN/')
install.packages("rmarkdown", repos='http://www.icesi.edu.co/CRAN/')
